import { Controller, Get, Param, Req, UseGuards } from '@nestjs/common';
import { AiService } from './ai.service';
import { AuthGuard } from '../auth/guards/auth.guard';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiParam,
  ApiBearerAuth,
  ApiProperty,
} from '@nestjs/swagger';

// كلاس لتوثيق شكل الاستجابة في Swagger
class AiAdviceResponseDto {
  @ApiProperty({
    example: 'Try breaking this large task into smaller steps to ensure progress.',
    description: 'The advice generated by the AI',
  })
  advice: string;

  @ApiProperty({
    example: 'ai',
    enum: ['ai', 'cache'],
    description: 'The source of the advice (Directly from AI or from Cache)',
  })
  source: string;
}

@ApiTags('AI Advice')
@ApiBearerAuth()
@UseGuards(AuthGuard)
@Controller('ai')
export class AiController {
  constructor(private readonly aiService: AiService) {}

  @Get('get-task-advice/:todoId')
  @ApiOperation({
    summary: 'Get smart advice for a specific task',
    description:
      'This endpoint uses the Llama 3.3 model via Groq to analyze the task title and description and provide actionable advice to the user.',
  })
  @ApiParam({
    name: 'todoId',
    description: 'The unique ID of the task',
    example: 7,
  })
  @ApiResponse({
    status: 200,
    description: 'Advice retrieved successfully.',
    type: AiAdviceResponseDto,
  })
  @ApiResponse({
    status: 401,
    description: 'User is not authenticated (Unauthorized).',
  })
  @ApiResponse({
    status: 403,
    description: 'User does not have permission to access this task.',
  })
  @ApiResponse({
    status: 404,
    description: 'Task not found.',
  })
  @ApiResponse({
    status: 500,
    description: 'Internal error while communicating with the AI service.',
  })
  async getTaskAdvice(@Param('todoId') todoId: number, @Req() req: any) {
    return this.aiService.getTaskAdvice(+todoId, +req.user.sub);
  }
}
